baseURL = "https://lock-up.it/"
languageCode = "it-it"
title = "LockUp"



pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = "G-W2QN5M51DJ"
  twitter_handle = "@protofra"
  showAuthorOnHomepage = false
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5